#' @title Overlay ClimaRep classifications into cumulative counts (climate redundancy)
#'
#' @description Combines multiple single-layer rasters (`tif`), outputs from `ClimaRep::mh_rep()` or `ClimaRep::mh_rep_ch()` for different input polygons, into a multi-layered `SpatRaster`, depending on the type of input.
#'
#' This function handles inputs from both `ClimaRep::mh_rep()` (which primarily contains **Analogue** cells) and `ClimaRep::mh_rep_ch()` (which includes **Stable**, **Lost**, and **Novel** cells). The output layers consistently represent counts of each input.
#' When `mh_rep()` outputs are aggregated, the resulting single-layer count is the climate redundancy: the number of reference polygons for which each cell is a climate analogue.
#'
#' \itemize{
#'   \item `change = FALSE` (default): inputs are treated as outputs of
#'         `ClimaRep::mh_rep()`. Only **Analogue** cells (value `1`) are counted,
#'         producing a single-layer cumulative count raster (climate redundancy).
#'   \item `change = TRUE`: inputs are treated as outputs of `ClimaRep::mh_rep_ch()`.
#'         **Lost** (`2`), **Stable** (`1`) and **Novel** (`3`) cells are counted
#'         separately, producing a three-layer `SpatRaster` ready for RGB plotting.
#' }
#'
#' @param folder_path `character`. The path to the directory containing the classification rasters (`.tif`) generated by `ClimaRep::mh_rep()` or `ClimaRep::mh_rep_ch()`. These rasters should primarily
#'  contain the categories: `1` (Stable/Analogue), `2` (Lost), and `3` (Novel).
#'  Category `0` (Non-analogue) will be ignored for the RGB output.
#' @param output_dir `character`. Path to the directory where the output file will be saved.
#' @param change `logical`. If `TRUE`, processes inputs as outputs from `ClimaRep::mh_rep_ch()` (Lost/Stable/Novel three-band RGB output). If `FALSE` (default), processes inputs as outputs from `ClimaRep::mh_rep()`.
#'
#' @return Writes the following outputs within the directory specified by `output_dir`:
#' When `ClimaRep::mh_rep()` results are used, the output layers consistently represent counts for **Analogue** categories across all input rasters.
#' When `ClimaRep::mh_rep_ch()` results are used, the output layers consistently represent counts for **Lost** (Red), **Stable** (Green), and **Novel** (Blue) categories across all input rasters. Designed for direct RGB plotting.
#' \itemize{
#'  \item A multi-layered `SpatRaster` (`ClimaRep_overlay.tif`) for RGB visualization.
#'  \item Individual `.tif` files for each band (Lost, Stable, Novel) in `individual_bands/` subdirectory.
#'  \item `Additional note`: The `ClimaRep::mh_rep()` function analyzes a single period. When its output is used, analogues cells are all categorized as Stable (value 1), while other categories (Lost and Novel) have a value of zero.
#' }
#'
#' @details
#' This function aggregates the per-polygon binary or categorical rasters produced by \code{\link{mh_rep}} or \code{\link{mh_rep_ch}} into cumulative count layers across
#' all input polygons. It is designed as a post-processing step to summarise where, and how often, a given category occurs in space when many polygons have been analysed.
#'
#'  The behaviour is controlled by the `change` argument:
#' \itemize{
#'   \item `change = FALSE` (default): inputs are treated as outputs of `ClimaRep::mh_rep()`. For each input raster, a binary layer is created where
#'         cells with value `1` (Analogue) are set to `1` and all other values to `0`. These layers are summed across all rasters to produce a single-layer
#'         cumulative count of how many polygons classify each cell as a climate analogue (climate redundancy).
#'   \item `change = TRUE`: inputs are treated as outputs of `ClimaRep::mh_rep_ch()`. Three independent cumulative count layers are
#'         produced, one for each change category: cells coded `2` (Lost), `1` (Stable), and `3` (Novel). Cells coded `0` (non-analogue) are ignored.
#'         The three count layers are stacked in the fixed order Lost (Red), Stable (Green), Novel (Blue), so the resulting `SpatRaster` is ready for direct RGB
#'         visualization with \code{terra::plotRGB()}, where colour mixtures intuitively reflect the spatial agreement among change types.
#' }
#'
#' Output structure within `output_dir`:
#' \itemize{
#'   \item `ClimaRep_overlay.tif`: the final multi-layer (or single-layer) `SpatRaster` of cumulative counts.
#'   \item `individual_bands/`: only created when `change = TRUE`. Contains one `.tif` per RGB channel `lost_count_R.tif`, `stable_count_G.tif`, `novel_count_B.tif` for users who prefer to handle each band separately.
#' }
#' @importFrom terra rast ifel app writeRaster nlyr values
#'
#' @examples
#' ClimaRep_overlay <- ClimaRep::rep_overlay(folder_path = system.file("extdata",
#'                                                                     package = "ClimaRep"),
#'                                          output_dir = file.path(tempdir(), "rep_overlay_output"),
#'                                          change = FALSE)
#' terra::plot(ClimaRep_overlay)
#' @export
rep_overlay <- function(folder_path,
                         output_dir = file.path(tempdir(), "ClimaRep_overlay"),
                         change = FALSE) {

  if (!is.character(folder_path) ||
      length(folder_path) != 1 || !dir.exists(folder_path)) {
    stop("Parameter 'folder_path' must be a character string and a valid directory.")
  }
  if (!is.character(output_dir) || length(output_dir) != 1) {
    stop("Parameter 'output_dir' must be a single character string.")
  }
  if (!is.logical(change) || length(change) != 1 || is.na(change)) {
    stop("Parameter 'change' must be a single logical value (TRUE or FALSE).")
  }
  message("Establishing output file structure.")
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  }
  raster_files <- list.files(folder_path, pattern = "\\.tif$", full.names = TRUE)
  if (length(raster_files) == 0) {
    stop("No '.tif' files found in the specified folder: ", folder_path)
  }
  message("Processing ", length(raster_files), " rasters from ", folder_path,
          " (mode: ", if (isTRUE(change)) "change [mh_rep_ch]" else " non-change [mh_rep]", ")")

  first_raster <- terra::rast(raster_files[1])

  if (isTRUE(change)) {
    dir_individual_bands <- file.path(output_dir, "individual_bands")
    if (!dir.exists(dir_individual_bands)) {
      dir.create(dir_individual_bands, recursive = TRUE, showWarnings = FALSE)
    }

    rgb_category_map  <- c("Lost" = 2, "Stable" = 1, "Novel" = 3)
    rgb_channel_names <- c("lost_count_R", "stable_count_G", "novel_count_B")

    count_rasters_for_rgb <- list(
      Lost   = first_raster * 0,
      Stable = first_raster * 0,
      Novel  = first_raster * 0)

    for (i in seq_along(raster_files)) {
      current_raster <- terra::rast(raster_files[i])
      for (cat_name in names(rgb_category_map)) {
        category_value <- rgb_category_map[cat_name]
        count_rasters_for_rgb[[cat_name]] <- count_rasters_for_rgb[[cat_name]] +
          terra::ifel(current_raster == category_value, 1, 0)
      }
    }
    for (cat_name in names(rgb_category_map)) {
      band_filename <- paste0(
        rgb_channel_names[which(names(rgb_category_map) == cat_name)], ".tif")
      terra::writeRaster(
        count_rasters_for_rgb[[cat_name]],
        file.path(dir_individual_bands, band_filename),
        overwrite = TRUE,
        datatype  = "INT2U")
    }

    final_stack <- c(count_rasters_for_rgb[["Lost"]],
                     count_rasters_for_rgb[["Stable"]],
                     count_rasters_for_rgb[["Novel"]])
    names(final_stack) <- rgb_channel_names

  } else {
    count_representativeness <- first_raster * 0

    for (i in seq_along(raster_files)) {
      current_raster <- terra::rast(raster_files[i])
      count_representativeness <- count_representativeness +
        terra::ifel(current_raster == 1, 1, 0)
    }

    final_stack <- count_representativeness
    names(final_stack) <- "analogues_count"
  }
  dir_output_file <- file.path(output_dir, "ClimaRep_overlay.tif")
  terra::writeRaster(final_stack,
                     dir_output_file,
                     overwrite = TRUE,
                     datatype  = "INT2U")

  message("All processes were completed")
  message(paste("Output files saved in:", output_dir))
  return(invisible(final_stack))
}
